# Generated by Django 5.2.3 on 2025-06-25 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_tourpackage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tourpackage',
            name='created_at',
        ),
        migrations.AddField(
            model_name='tourpackage',
            name='expiry_date',
            field=models.DateField(default='2025-12-31'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('user', 'User'), ('vendor', 'Vendor')], max_length=10),
        ),
        migrations.AlterField(
            model_name='tourpackage',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
        migrations.AlterField(
            model_name='tourpackage',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
