# Generated by Django 5.2.3 on 2025-06-26 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_booking'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='contact_email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='num_people',
            new_name='number_of_people',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='contact_phone',
            new_name='phone',
        ),
        migrations.AlterField(
            model_name='tourpackage',
            name='category',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='tourpackage',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='tourpackage',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
